### Healthcheck: Verificar el estado del servidor (GET)
GET http://localhost:3003/ms/mdr/v1/healthcheck
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
X-Security-Signature: signature_TYPE=SHARSA;PAYLOADSIGNED=HASHEDPAYLOADBYPEMANDTYPE
Accept: application/json

###

### Auth: Autenticación (Login) usando credenciales (POST)
# Se envían las credenciales para obtener un token JWT.
POST http://localhost:3003/ms/mdr/v1/auth/login
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5

{
  "username": "test",
  "password": "test"
}

###

### Auth: Validación de Token (POST)
# Se envía el token para validar su autenticidad.
POST http://localhost:3003/ms/mdr/v1/auth/validate
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoidXNlciIsImlhdCI6MTczNzI0MDk5OH0.cWqy-gkXo-vu1PNJXGkx9F9S18sj3QhllSrnaYYXfNsj5WoOaccDU5OuPKYZlfsQSpVWV1CxEfKzv0mELNf5KFvi0x4Eevf077mMXYyOpamNoCX4xUeehum-WqcDY6jHKJXGvn1K16A0bQ9wJH1WLhpq4D4lG-ord0AMZeDLAf3P_FqFzekYEshXx6bmQAQfRMvSR9lLfwXQ3FKDnUFJncZN3fA9eIbiLcM7eCytZfCKMe6SxST7q1dOFkWAsxpp1QPKxK-YYUz2M9Sk7U8yurLkPTz81rtpFZMOt-rSKYGEdk9nmM_sDIuA0tGgahN3ixAuDYjSmNYNKCLh7sxZZw

{
  "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoidXNlciIsImlhdCI6MTczNzI0MDk5OH0.cWqy-gkXo-vu1PNJXGkx9F9S18sj3QhllSrnaYYXfNsj5WoOaccDU5OuPKYZlfsQSpVWV1CxEfKzv0mELNf5KFvi0x4Eevf077mMXYyOpamNoCX4xUeehum-WqcDY6jHKJXGvn1K16A0bQ9wJH1WLhpq4D4lG-ord0AMZeDLAf3P_FqFzekYEshXx6bmQAQfRMvSR9lLfwXQ3FKDnUFJncZN3fA9eIbiLcM7eCytZfCKMe6SxST7q1dOFkWAsxpp1QPKxK-YYUz2M9Sk7U8yurLkPTz81rtpFZMOt-rSKYGEdk9nmM_sDIuA0tGgahN3ixAuDYjSmNYNKCLh7sxZZw"
}

###

### MDR: Todas los Card Brand Merchant Discount Rate (GET)
# Se envía el token para validar su autenticidad y consultar las tasas para Amex, Discover, Mastercard y Visa.
GET http://localhost:3003/ms/mdr/v1/card-brand-mdr/get-all-mdr
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoidXNlciIsImlhdCI6MTczNzI0MDk5OH0.cWqy-gkXo-vu1PNJXGkx9F9S18sj3QhllSrnaYYXfNsj5WoOaccDU5OuPKYZlfsQSpVWV1CxEfKzv0mELNf5KFvi0x4Eevf077mMXYyOpamNoCX4xUeehum-WqcDY6jHKJXGvn1K16A0bQ9wJH1WLhpq4D4lG-ord0AMZeDLAf3P_FqFzekYEshXx6bmQAQfRMvSR9lLfwXQ3FKDnUFJncZN3fA9eIbiLcM7eCytZfCKMe6SxST7q1dOFkWAsxpp1QPKxK-YYUz2M9Sk7U8yurLkPTz81rtpFZMOt-rSKYGEdk9nmM_sDIuA0tGgahN3ixAuDYjSmNYNKCLh7sxZZw
