### Healthcheck Endpoint
GET http://localhost:3000/api/healthcheck

### Login Endpoint
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}


### Crear un Nuevo Pago
POST http://localhost:3000/api/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjEsImlhdCI6MTczNDkwNzM1NCwiZXhwIjoxNzM0OTEwOTU0fQ.qSDyCLHkaM8y6ETQc9XcUEAkn1szz0JP8SMDhauB9IDlnNBeSE7tos5sXnWWRGlUACdPeN4YX9bRiLlhI6E_ir3v95rB7U6DO9NNV-4DNZNaWwARbFCjB0UHb93pMASTPkgVP_LezbYSkYHIjq9qrrQtVGiqalT5J8EjuIupTxVuZcSU-LeoBFDMs5DTho8OicihrAOOpfZjwl-rEy1eE-EaQDPW9BqMXMFe4QuoRpT00T2UIbrSlOEl-U9cCVT1m9dtMeQ4ZFctCuXPshqAKxWodmtMDZ0UtNpGXh97azeu5nijydoz4pFv1CyOzb8t3OIEMZB3_Gs3wfEwL3fT3Q

{
  "transaction_id": "txn-2001-abcdesf123459",
  "card_number": "411111******1234",
  "amount": 150.25,
  "currency": "CLP",
  "timestamp": "2024-06-01T10:15:00Z",
  "merchant": {
    "merchant_id": "m-3001",
    "name": "Restaurante Don Pepe",
    "category": "Restaurante",
    "location": {
      "address": "Calle Larga 123",
      "city": "Santiago",
      "country": "Chile",
      "latitude": -33.4489,
      "longitude": -70.6693
    }
  },
  "transaction_type": "Pago",
  "auth_code": "AUTH123456",
  "response_code": "00",
  "terminal_id": "term-4001",
  "issuer": {
    "bank_id": "bank-5001",
    "name": "Banco Estado",
    "country": "Chile"
  },
  "cardholder_verification_method": "Firma",
  "emv_data": {
    "application_id": "A0000000031010",
    "application_label": "VISA CREDITO",
    "transaction_counter": 5,
    "unpredictable_number": "1A2B3C4D",
    "issuer_application_data": "01020304"
  },
  "additional_data": {
    "installments": 1,
    "tip_amount": 0.00,
    "cashback_amount": 0.00
  }
}
