### Healthcheck: Verificar estado del servidor
GET http://localhost:3003/ms/mdr/v1/healthcheck
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
X-Security-Signature: signature_TYPE=SHARSA;PAYLOADSIGNED=HASHEDPAYLOADBYPEMANDTYPE
Accept: application/json


### Auth: Generación de Token (Login)
POST http://localhost:3003/ms/mdr/v1/auth/login
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5

{
  "username": "test",
  "password": "test123"
}


### Auth: Validar Token
POST http://localhost:3003/ms/mdr/v1/auth/validate
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoiVVNFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzM3OTE4OTc5fQ.S1OY1lPYYfCg-vUeXQ8_COupspHWD3fwyLlsuxZnMEklmmj1J3vg4YtPhvo2MlYYYr4-GygBFc2hCVaCfrndN97DjluAuQqjBBpkVug15-qhvp3wDGXLgyyi7WViQVLxLT46i9gxe2CnzduiPe_8qEEB8WnAVI3cyD1IszGfQdfhCBf9xVWWcigSnRmDlsgLbtPOpvA-C7A01H6qL4ZESktjdfJTxBj640Ax7Gv9yIwp8kaFDbKNpTfB4TKzeZl5GpFUh_OxoxgtO0w3c_jstkjE3rL1Bub57nmQAi-yH_yvcsPkbXuZ9mhBJ8Q8Dhrz9Hh4IM1HMWx2jnpVxg70Kw

{
  "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoiVVNFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzM3OTE4OTc5fQ.S1OY1lPYYfCg-vUeXQ8_COupspHWD3fwyLlsuxZnMEklmmj1J3vg4YtPhvo2MlYYYr4-GygBFc2hCVaCfrndN97DjluAuQqjBBpkVug15-qhvp3wDGXLgyyi7WViQVLxLT46i9gxe2CnzduiPe_8qEEB8WnAVI3cyD1IszGfQdfhCBf9xVWWcigSnRmDlsgLbtPOpvA-C7A01H6qL4ZESktjdfJTxBj640Ax7Gv9yIwp8kaFDbKNpTfB4TKzeZl5GpFUh_OxoxgtO0w3c_jstkjE3rL1Bub57nmQAi-yH_yvcsPkbXuZ9mhBJ8Q8Dhrz9Hh4IM1HMWx2jnpVxg70Kw"
}


### MDR: Todas las tasas (Amex, Discover, Mastercard, Visa)
GET http://localhost:3003/ms/mdr/v1/card-brand-mdr/get-all-mdr
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoiVVNFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzM3OTE4OTc5fQ.S1OY1lPYYfCg-vUeXQ8_COupspHWD3fwyLlsuxZnMEklmmj1J3vg4YtPhvo2MlYYYr4-GygBFc2hCVaCfrndN97DjluAuQqjBBpkVug15-qhvp3wDGXLgyyi7WViQVLxLT46i9gxe2CnzduiPe_8qEEB8WnAVI3cyD1IszGfQdfhCBf9xVWWcigSnRmDlsgLbtPOpvA-C7A01H6qL4ZESktjdfJTxBj640Ax7Gv9yIwp8kaFDbKNpTfB4TKzeZl5GpFUh_OxoxgtO0w3c_jstkjE3rL1Bub57nmQAi-yH_yvcsPkbXuZ9mhBJ8Q8Dhrz9Hh4IM1HMWx2jnpVxg70Kw


### MDR: Tasas por marca - AMEX
GET http://localhost:3003/ms/mdr/v1/card-brand-mdr/get-all-mdr-by-card-brand/amex
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoiVVNFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzM3OTE4OTc5fQ.S1OY1lPYYfCg-vUeXQ8_COupspHWD3fwyLlsuxZnMEklmmj1J3vg4YtPhvo2MlYYYr4-GygBFc2hCVaCfrndN97DjluAuQqjBBpkVug15-qhvp3wDGXLgyyi7WViQVLxLT46i9gxe2CnzduiPe_8qEEB8WnAVI3cyD1IszGfQdfhCBf9xVWWcigSnRmDlsgLbtPOpvA-C7A01H6qL4ZESktjdfJTxBj640Ax7Gv9yIwp8kaFDbKNpTfB4TKzeZl5GpFUh_OxoxgtO0w3c_jstkjE3rL1Bub57nmQAi-yH_yvcsPkbXuZ9mhBJ8Q8Dhrz9Hh4IM1HMWx2jnpVxg70Kw


### MDR: Tasas por marca - DISCOVER
GET http://localhost:3003/ms/mdr/v1/card-brand-mdr/get-all-mdr-by-card-brand/discover
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoiVVNFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzM3OTE4OTc5fQ.S1OY1lPYYfCg-vUeXQ8_COupspHWD3fwyLlsuxZnMEklmmj1J3vg4YtPhvo2MlYYYr4-GygBFc2hCVaCfrndN97DjluAuQqjBBpkVug15-qhvp3wDGXLgyyi7WViQVLxLT46i9gxe2CnzduiPe_8qEEB8WnAVI3cyD1IszGfQdfhCBf9xVWWcigSnRmDlsgLbtPOpvA-C7A01H6qL4ZESktjdfJTxBj640Ax7Gv9yIwp8kaFDbKNpTfB4TKzeZl5GpFUh_OxoxgtO0w3c_jstkjE3rL1Bub57nmQAi-yH_yvcsPkbXuZ9mhBJ8Q8Dhrz9Hh4IM1HMWx2jnpVxg70Kw


### MDR: Tasas por marca - MASTERCARD
GET http://localhost:3003/ms/mdr/v1/card-brand-mdr/get-all-mdr-by-card-brand/mastercard
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoiVVNFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzM3OTE4OTc5fQ.S1OY1lPYYfCg-vUeXQ8_COupspHWD3fwyLlsuxZnMEklmmj1J3vg4YtPhvo2MlYYYr4-GygBFc2hCVaCfrndN97DjluAuQqjBBpkVug15-qhvp3wDGXLgyyi7WViQVLxLT46i9gxe2CnzduiPe_8qEEB8WnAVI3cyD1IszGfQdfhCBf9xVWWcigSnRmDlsgLbtPOpvA-C7A01H6qL4ZESktjdfJTxBj640Ax7Gv9yIwp8kaFDbKNpTfB4TKzeZl5GpFUh_OxoxgtO0w3c_jstkjE3rL1Bub57nmQAi-yH_yvcsPkbXuZ9mhBJ8Q8Dhrz9Hh4IM1HMWx2jnpVxg70Kw


### MDR: Tasas por marca - VISA
GET http://localhost:3003/ms/mdr/v1/card-brand-mdr/get-all-mdr-by-card-brand/visa
Content-Type: application/json; charset=utf-8
X-Security-Header-Key: 7374b7ba0d5a8fa0c866097d401a96c5
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJyb2xlIjoiVVNFUiIsInVzZXJJZCI6MiwiaWF0IjoxNzM3OTE4OTc5fQ.S1OY1lPYYfCg-vUeXQ8_COupspHWD3fwyLlsuxZnMEklmmj1J3vg4YtPhvo2MlYYYr4-GygBFc2hCVaCfrndN97DjluAuQqjBBpkVug15-qhvp3wDGXLgyyi7WViQVLxLT46i9gxe2CnzduiPe_8qEEB8WnAVI3cyD1IszGfQdfhCBf9xVWWcigSnRmDlsgLbtPOpvA-C7A01H6qL4ZESktjdfJTxBj640Ax7Gv9yIwp8kaFDbKNpTfB4TKzeZl5GpFUh_OxoxgtO0w3c_jstkjE3rL1Bub57nmQAi-yH_yvcsPkbXuZ9mhBJ8Q8Dhrz9Hh4IM1HMWx2jnpVxg70Kw
