### Healthcheck Endpoint
GET http://localhost:3000/api/healthcheck

### Login Endpoint
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}


### Crear un Nuevo Pago
POST http://localhost:3000/api/payments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzM0OTE2MTYxLCJleHAiOjE3MzQ5MTk3NjF9.LIQZAaSLRAiru_r9HM-X3ig454PM2XoMkO1NaIebWDEATwycqi87yxO7gUsrrryV3Mu9cVnWBkxIIdWywe2rQo71txMAI9pP5wEXRfC6QMaeBCKaaNtnIr9cs8syGUuqb1af8pppDxSE3EadQXe_q7ShUKZO_kyFw43xc2QdyscmxQ9m3COMFgrl87x6bFYGqnCKQn4qfAD6Hm50oem9qntZ3gggRmoOFfOKs4xAv8T7aedr_p_V2SgvkksOVIUE4QIVyNGG6sSjzoIrPV7jU2UpsyRifl71ELzCMk7xdZiv24koWzSK-HCfGPatLXY8BvEuIlbmTUGykGucP6bHNA

{
  "transaction_id": "txn-2001-abcdesf123459",
  "card_number": "411111******1234",
  "amount": 150.25,
  "currency": "CLP",
  "timestamp": "2024-06-01T10:15:00Z",
  "merchant": {
    "merchant_id": "m-3001",
    "name": "Restaurante Don Pepe",
    "category": "Restaurante",
    "location": {
      "address": "Calle Larga 123",
      "city": "Santiago",
      "country": "Chile",
      "latitude": -33.4489,
      "longitude": -70.6693
    }
  },
  "transaction_type": "Pago",
  "auth_code": "AUTH123456",
  "response_code": "00",
  "terminal_id": "term-4001",
  "issuer": {
    "bank_id": "bank-5001",
    "name": "Banco Estado",
    "country": "Chile"
  },
  "cardholder_verification_method": "Firma",
  "emv_data": {
    "application_id": "A0000000031010",
    "application_label": "VISA CREDITO",
    "transaction_counter": 5,
    "unpredictable_number": "1A2B3C4D",
    "issuer_application_data": "01020304"
  },
  "additional_data": {
    "installments": 1,
    "tip_amount": 0.00,
    "cashback_amount": 0.00
  }
}
